### ISSUE TITLE
How could it be faster to download the image?

### ISSUE THREAD

**Issue by suoba** [oguzhaninan/Gallery-With-Pinterest-Pins#1]
Thanks for your code. It's very useful for me, and also easy to use.
But it's really too slow to download images,  It takes 1~2 Minute to download one image.
Is that any way to make it faster?

**Comment by oguzhaninan** [comment]
I fix the problem

**Comment by suoba** [comment]
New problem with your new code....

> python pinterest_gallery.py -i 1 -d 0 -l 10 -o example
> User Name: cinders1211
> Board Name: bears
> Traceback (most recent call last):
>   File "pinterest_gallery.py", line 119, in <module>
>     for im in data["data"]:
> TypeError: 'NoneType' object is not iterable

**Comment by oguzhaninan** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/16149251/18379854/4693421c-767d-11e6-8505-2da2b8b6adb5.png)
You have to use python3 and must be token

**Comment by suoba** [comment]
You are right ,my bad ,forget to update the token.
And the download speed is much faster than before.
Thank you very much.

**Comment by oguzhaninan** [comment]
you're welcome

**Comment by tigefa4u** [comment]
whereis i can get the token? :smile_cat:

**Comment by oguzhaninan** [comment]
https://developers.pinterest.com/docs/getting-started/introduction/
